version: '3.8'
services:
  mingo-chan:
    build: .
    ports:
      - 1928:1928
    depends_on:
      - redis
      - database
  redis:
    image: redis:latest
    container_name: 'redis_mingo-chan_data_container'
    volumes:
      - redis_mingo-chan_data_volume:/redis/data/db
      - ./config/redis.conf:/redis.conf
    command: ['redis-server', '/redis.conf']
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      # TODO: PROTECT THE DAMN PORT IN THE FIREWALL ON VPS'S!
      - 6379:6379
  database:
    image: mongo:4.4
    container_name: 'mongodb_mingo-chan_data_container'
    volumes:
      # - ALLOW_EMPTY_PASSWORD=yes
      - mongodb_mingo-chan_data_volume:/mongodb/data/db
      #- MONGO_INITDB_ROOT_USERNAME=root
      #- MONGO_INITDB_ROOT_PASSWORD=rootpassword
      #- MONGO_INITDB_DATABSE=MingoChan
    ports:
      # TODO: PROTECT THE DAMN PORT IN THE FIREWALL ON VPS'S!
      - 27017:27017
volumes:
  redis_mingo-chan_data_volume:
    driver: local
  mongodb_mingo-chan_data_volume:
